/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProvisionRouteImport } from './routes/provision'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvisionIndexRouteImport } from './routes/provision.index'
import { Route as StatusTenantIdRouteImport } from './routes/status.$tenantId'
import { Route as ProvisionSuccessRouteImport } from './routes/provision.success'
import { Route as ProvisionCancelRouteImport } from './routes/provision.cancel'

const ProvisionRoute = ProvisionRouteImport.update({
  id: '/provision',
  path: '/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionIndexRoute = ProvisionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvisionRoute,
} as any)
const StatusTenantIdRoute = StatusTenantIdRouteImport.update({
  id: '/status/$tenantId',
  path: '/status/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionSuccessRoute = ProvisionSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ProvisionRoute,
} as any)
const ProvisionCancelRoute = ProvisionCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ProvisionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/provision': typeof ProvisionRouteWithChildren
  '/provision/cancel': typeof ProvisionCancelRoute
  '/provision/success': typeof ProvisionSuccessRoute
  '/status/$tenantId': typeof StatusTenantIdRoute
  '/provision/': typeof ProvisionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/provision/cancel': typeof ProvisionCancelRoute
  '/provision/success': typeof ProvisionSuccessRoute
  '/status/$tenantId': typeof StatusTenantIdRoute
  '/provision': typeof ProvisionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/provision': typeof ProvisionRouteWithChildren
  '/provision/cancel': typeof ProvisionCancelRoute
  '/provision/success': typeof ProvisionSuccessRoute
  '/status/$tenantId': typeof StatusTenantIdRoute
  '/provision/': typeof ProvisionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/provision'
    | '/provision/cancel'
    | '/provision/success'
    | '/status/$tenantId'
    | '/provision/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/provision/cancel'
    | '/provision/success'
    | '/status/$tenantId'
    | '/provision'
  id:
    | '__root__'
    | '/'
    | '/provision'
    | '/provision/cancel'
    | '/provision/success'
    | '/status/$tenantId'
    | '/provision/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProvisionRoute: typeof ProvisionRouteWithChildren
  StatusTenantIdRoute: typeof StatusTenantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provision': {
      id: '/provision'
      path: '/provision'
      fullPath: '/provision'
      preLoaderRoute: typeof ProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provision/': {
      id: '/provision/'
      path: '/'
      fullPath: '/provision/'
      preLoaderRoute: typeof ProvisionIndexRouteImport
      parentRoute: typeof ProvisionRoute
    }
    '/status/$tenantId': {
      id: '/status/$tenantId'
      path: '/status/$tenantId'
      fullPath: '/status/$tenantId'
      preLoaderRoute: typeof StatusTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provision/success': {
      id: '/provision/success'
      path: '/success'
      fullPath: '/provision/success'
      preLoaderRoute: typeof ProvisionSuccessRouteImport
      parentRoute: typeof ProvisionRoute
    }
    '/provision/cancel': {
      id: '/provision/cancel'
      path: '/cancel'
      fullPath: '/provision/cancel'
      preLoaderRoute: typeof ProvisionCancelRouteImport
      parentRoute: typeof ProvisionRoute
    }
  }
}

interface ProvisionRouteChildren {
  ProvisionCancelRoute: typeof ProvisionCancelRoute
  ProvisionSuccessRoute: typeof ProvisionSuccessRoute
  ProvisionIndexRoute: typeof ProvisionIndexRoute
}

const ProvisionRouteChildren: ProvisionRouteChildren = {
  ProvisionCancelRoute: ProvisionCancelRoute,
  ProvisionSuccessRoute: ProvisionSuccessRoute,
  ProvisionIndexRoute: ProvisionIndexRoute,
}

const ProvisionRouteWithChildren = ProvisionRoute._addFileChildren(
  ProvisionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProvisionRoute: ProvisionRouteWithChildren,
  StatusTenantIdRoute: StatusTenantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
